feat/tb-39 adds endpoints for 2FA
thinblock/tb-core-api pull request #13
Opened 2018-08-15 10:22 UTC by abdullahtariq91

adds 2fa functionality 
- adds endpoint to login with 2fa
- adds endpoint to update user profile for 2fa
- adds login checks
- adds 2fa checks
- adds test cases
- ToDo: make utils/otp generic for other cases
- ToDo: make changes in other test cases

2018-08-15 10:26 UTC, abdullahtariq91 commented
Will need to update test cases for other endpoints.

2018-08-16 09:20 UTC, hamxabaig requested changes
@abdullahtariq91 awesome. Some changes and questions. Look at them when you find time.

2018-08-16 09:20 UTC, hamxabaig commented on app/modules/auth/login/login.controller.ts
> +            user: { id: user.id, phone: user.phone, otp: response.otp },
We don't need to send the OTP in response, otherwise whats the purpose of OTP. It will only be known to the user. Just reply with success and message

2018-08-16 09:20 UTC, hamxabaig commented on app/modules/auth/signup/signup.controller.ts
> +        user_id: returnUser.id, enable_otp: body.enable_otp
The settings will not be in `signup` body response. It'll have its own endpoint to update settings (later). Consider this a settings page in frontend app where user checks (later when he has already signed up) the checkbox to setup 2FA.
So by default user signing up, it'll be false and not taken in signup body.

2018-08-16 09:20 UTC, hamxabaig commented on app/modules/auth/signup/signup.route.ts
> +              enable_otp: Joi.bool().required(),
Don't need it here.

2018-08-16 09:20 UTC, hamxabaig commented on app/modules/auth/signup/signup.route.ts
> +            Signs up user with name, email, password, phone, and two factor authorization
Don't forget to revert it to before.

2018-08-16 09:20 UTC, hamxabaig commented on utils/otp.ts
> +    const accountSid = process.env.TWILIO_SID;
Please add these to `env.ts` file. Using separate twilio object there.

2018-08-16 09:20 UTC, hamxabaig commented on utils/otp.ts
> +      await client.messages.create({
What if some error happened? On error, you should delete the record you created.

2018-08-16 09:20 UTC, hamxabaig commented on utils/otp.ts
> +
Add tests for this service. Also maybe better to move it into its folder

2018-08-16 09:20 UTC, hamxabaig commented on utils/otp.ts
> +    if (process.env.NODE_ENV !== 'production') {
Use `env.ts` for any env related stuff. Its not gonna be manageable later if we use raw `process.env`

2018-08-16 09:20 UTC, hamxabaig commented on utils/otp.ts
> +      await client.messages.create({
Doing this in a single try/catch will make confusion here. We'll want to nicely format our errors. Like when reading db the error should be a 500 but when the phone code is not sent, it must be a 200 with error message as "Unable to send the message to the given number"
To separate the errors from each other you can use `await-to-js` package which i added. Like here:
https://github.com/thinblock/tb-core-api/blob/HEAD/app/middlewares/auth.ts#L32-L33

2018-08-16 09:20 UTC, hamxabaig commented on utils/otp.ts
> +      { where: { user_id: String(user_id) }
Why string, isn't it a number?
This is why you should use TypeScript lot more.
```javascript
<IPhoneVerification> await PhoneVerificationCode.findOne(
       { where: <IPhoneVerification> { user_id: String(user_id) }
);
```

2018-08-16 09:20 UTC, hamxabaig commented on utils/otp.ts
> +    const otp = Math.floor(1000 + Math.random() * 9000).toString();
Lets add this to `helpers.ts` so we can use it in other places.

2018-08-16 09:20 UTC, hamxabaig commented on migrations/2018_08_07_11_26_17_305_tb_auth_users.ts
> -
Why delete the migrations? You should also add your own migration file which i haven't seen here. How did you migrated?

2018-08-16 09:20 UTC, hamxabaig commented on app/modules/auth/two_factor_authorization/two_factor_authorization.controller.ts
> +  public async put(req: IRequest, res: IResponse, next: restify.Next) {
This should be in the settings endpoint IMO. Much more manageable later to add new things, Otherwise we'll end up with bazillion endpoints. What do you think ? 
PUT `/api/users/me/settings`

2018-08-16 09:20 UTC, hamxabaig commented on app/modules/auth/two_factor_authorization/two_factor_authentication.route.unit.spec.ts
> +          .expects('findOne')
also add what arguments its expecting in all of the test cases otherwise, these are just weak tests which will never break if i change any of the arguments in the functions there.

2018-08-16 09:20 UTC, hamxabaig commented on app/modules/auth/two_factor_authorization/two_factor_authorization.controller.ts
> +      const user = <IUser> await User.findOne({ where: { phone: phone } });
Try to use ES6 features like `where: { phone }`

2018-08-17 07:50 UTC, abdullahtariq91 commented on app/modules/auth/login/login.controller.ts
> +            user: { id: user.id, phone: user.phone, otp: response.otp },
Forgot to remove after testing. Thanks! 👍

2018-08-17 07:51 UTC, abdullahtariq91 commented on app/modules/auth/signup/signup.controller.ts
> +        user_id: returnUser.id, enable_otp: body.enable_otp
Will create a separate endpoint for user settings. Anything else that needs to be set there, or enable_otp is enough for now?

2018-08-17 07:53 UTC, abdullahtariq91 commented on migrations/2018_08_07_11_26_17_305_tb_auth_users.ts
> -
Thought they were added as an example. Will keep the files there now onwards.

2018-08-17 08:01 UTC, hamxabaig commented on app/modules/auth/signup/signup.controller.ts
> +        user_id: returnUser.id, enable_otp: body.enable_otp
`enable_top` along with `phone` to be saved

2018-08-19 22:27 UTC, abdullahtariq91 commented on utils/otp.ts
> +
Need help with testing async function.
Function returns a promise, but doesn't wait for it to resolve.

2018-08-19 22:28 UTC, abdullahtariq91 commented on utils/otp.ts
> +      await client.messages.create({
Record will be deleted next time the function is called.

2018-08-20 06:09 UTC, hamxabaig commented on utils/otp.ts
> +
add an example code, maybe i can help?

2018-08-28 08:50 UTC, hamxabaig commented
@abdullahtariq91 add arguments in mocked functions just like you did with #14 Let me know when done. I'll review and merge.

2018-08-29 09:10 UTC, merged